import magickapp from './magickapp.js'

(async (args) => {
  try {
    let arrOfCommandsRun = await magickapp(args)
    if(args.length <= 2) {
      // do nothing
    } else {
      console.info(`${arrOfCommandsRun.length} new images generated by Magickapp via Imagemagick :-) `)
    }
    process.exit()
  } catch(err) {
    console.error(err)
    process.exit()
  }

})(process.argv)